### PR TITLE
First Draft - Community Guidelines Proposal

### PR DESCRIPTION
**Pull request by RyanPallesen**

### CODE REVIEW

**Comment by KomradeSpectre** [comment]
I'm going to hard vote this down. Especially since this is a hot button topic, and I can't trust you to be impartial on it. I advise anyone else to do the same.

**Comment by RyanPallesen** [comment]
> I'm going to hard vote this down. Especially since this is a hot button topic, and I can't trust you to be impartial on it. I advise anyone else to do the same.

Then edit the conduct as you see fit, this isn't just me making up stuff, it's a starting off point for the community to decide what is and is not allowed

Edit; Also I likely won't be moderating this, It will be the existing moderator team and other users, so my impartiality isn't meaningful?

**Comment by KomradeSpectre** [comment]
I've overseen plenty of communities do this without necessity (since the moderators handled it fine before) only for it to get abused by people with vested social political interests. I heavily recommend against this out of experience. The moderators are perfectly capable of handling things as is.

**Comment by RyanPallesen** [comment]
The problem being that there is no set rules and people are doing harmful things that the mods and owners have had to step in on, but had no fallback as to why something is not allowed.

Please explain to me why having a rulesheet saying 'follow the discord ToS and don't post child porn' is not desirable?

**Comment by xiaoxiao921** [comment]
That draft seems fine to me, but i'm not sure why it is taking place here, since it seems related to the Discord server itself, shouldn't that be taking place in a channel for discussing server management ?

**Comment by RyanPallesen** [comment]
> That draft seems fine to me, but i'm not sure why it is taking place here, since it seems related to the Discord server itself, shouldn't that be taking place in a channel for discussing server management ?

Mythic asked for someone to draft it up, and then asked me to post it here as a PR with formatting

**Comment by KomradeSpectre** [comment]
First off, it's not written by the currently elected/assigned moderators or admins but by a person who has regularly been seen getting sensitive in the #memes channel on the discord.
Secondly, stop using children as a cudgel here, since that is a common sense thing not to do, and it gets dealt with a simple ping of a moderator if they didn't already catch it.

I'm fairly confident in the already assigned moderator's abilities to do their jobs. If they want a fallback, they themselves should write it up among themselves.

**Comment by RyanPallesen** [comment]
> First off, it's not written by the currently elected/assigned moderators or admins but by a person who has regularly been seen getting sensitive in the #memes channel on the discord.
> Secondly, stop using children as a cudgel here, since that is a common sense thing not to do, and it gets dealt with a simple ping of a moderator if they didn't already catch it.
> 
> I'm fairly confident in the already assigned moderator's abilities to do their jobs. If they want a fallback, they themselves should write it up among themselves.

considering this was directly asked for by the owner and isn't just me (Again, PLEASE EDIT THIS IF YOU DON'T LIKE IT)

If you find in any way that the first, initial draft is in error; bring it up and submit a PR. This is a community decision and project, I am not fully responsible nor at all in power. Arguing that I'm biased or that my draft is wrong is meaningless, put into action what you think would be good as a PR.

**Comment by xiaoxiao921** [comment]
> First off, it's not written by the currently elected/assigned moderators or admins but by a person who has regularly been seen getting sensitive in the #memes channel on the discord.
> Secondly, stop using children as a cudgel here, since that is a common sense thing not to do, and it gets dealt with a simple ping of a moderator if they didn't already catch it.
> 
> I'm fairly confident in the already assigned moderator's abilities to do their jobs. If they want a fallback, they themselves should write it up among themselves.

This is a draft / proposition, this community is, well, community based, so anyone who is currently active within the community is welcomed to do change / put the community forward. Afaik most people like mods / admins all have their life busy, so offloading the workload from them for this kind of stuff is nice

**Comment by KomradeSpectre** [comment]
I'm not exactly sure how this is going to offload it from them. They'll still have to enforce it, and having any lines to be walked in this will introduce a cycle of people toeing the line, then people putting more vested interests/social interests in. Then more people toeing the line, and the cycle goes on. See communities like tgstation13 for this kind of downward spiral. They are community based, but this kind of action by their community ended up with subversive action over the years. I heavily recommend existing administrative staff do this instead of a community.

**Comment by KomradeSpectre** [comment]
Additionally, as my last post in this PR, please take a look at the already existing rule/conduct infrastructure.
Perhaps Mythic forgot about it.

https://discordapp.com/channels/562704639141740588/563458110665129985/563458722605694976

**Comment by ebkr** [comment]
It doesn't really matter who wrote it as it's really just general rules on how to be somewhat decent in the server.

They might have to enforce it, but they don't have to take the time to write it themselves. If it's acceptable and covers the scenarios you'd expect then I don't see why this would be an issue?

**Comment by RyanPallesen** [comment]
> Additionally, as my last post in this PR, please take a look at the already existing rule/conduct infrastructure.
> Perhaps Mythic forgot about it.

Most of these seem to not be upheld any longer. If these rules were actually followed, numerous people would have been banned by now.

Either the server is lacking in staff, or the rules are unclear and need to be re-adjusted.
The direction in which the rules are adjusted isn't important, as long as they are clear and upheld.

**Comment by KirbyKat21** [comment]
> It doesn't really matter who wrote it as it's really just general rules on how to be somewhat decent in the server.
> 
> They might have to enforce it, but they don't have to take the time to write it themselves. If it's acceptable and covers the scenarios you'd expect then I don't see why this would be an issue?

The issue is there's no place for half the verbiage in there. Rules this specific beget people who wish to make appeals based on their status and cite the rules to outline why they should be treated better. As a transgender individual myself i don't really think just because I'm of a certain demographic that i should have a rule made for me. I could easily turn any slightly negative comment made against me to be outlined as transphobic just because i am trans. Whereas if it was anyone else it would likely just be some kind of wrist slap. I don't think having a protected group above general users being outlined in rules like this is smart. It just makes too many lines in the sand and segments the userbase based on their identity.

**Comment by KomradeSpectre** [comment]
When it is filled with loaded language like
> do not defame, libel, ridicule, mock,

I severely lack trust in the foundations of it. Mod creators, players, etc, are ridiculed or mocked all the time in the discord. Most of the time for publicly stupid things that they've done or said, other times in jest. This is one of the things that can absolutely and will absolutely be used to subvert the community by users for example, or not enforced at all, so why have it?

**Comment by RyanPallesen** [comment]
> When it is filled with loaded language like
> 
> > do not defame, libel, ridicule, mock,


That is taken directly from the discord Terms of Service, which are rules we should already be upholding and have all agreed to
https://discord.com/terms

**Comment by KomradeSpectre** [comment]
I challenge you to give me, examples of each one of these that have not been dealt with in the community and your reasoning for including them in this suggested CoC, impartially.

**Comment by Reinms** [comment]
Yeah this is basically straight copypaste of discord ToS along with tons of other online platforms, (pretty sure github is extremely similar?) I don't see anything at all that is cause for concern here.

**Comment by DarastrixJames** [comment]
After reading through this, I've come to a solid conclusion.

Understanding that this is decided by "Vote from the masses," I'm bringing something different to the table.

**Community Guidelines: More Lenient (And with some other stuff.)**
Essentially, I believe a more lenient and "Grow some backbone" ideology would fit the server better.  We can't really cater to everyone, regardless if they're being actually offended or bothered by something.  It is easier to only enforce a rule or stop a situation when it legitimately gets out of hand or breaks the TOS on a, and read this carefully, _LEGAL LEVEL_.  As with the nature of anonymity on the internet, we cannot trust people to be serious or ironic, so why waste the energy on it?

**The Meme Chat**
People are going to post some heinous things.  Whether it be racial, or whatever words other people use, you will ALWAYS find them.  We cannot keep track of every single time someone, somehow, gets hurt or offended, so why waste energy on it?  Discord does not ban servers that break TOS unless on a, and read this carefully, _LEGAL LEVEL_, so we have nothing to worry about unless someone tries to post CP or asks for them.  Obviously, the community shows quick signs to react to things that are common-deemed inhumane or outright insane, like extreme gore, CP, and Doxing.  But, when it's something that's just making fun of a group, or all groups, or a person, and it's just a joke?  You're wasting your time silencing that.  Nobody is going to care, and if people do, they need to "grow some backbone," which brings this back to my final point.

**Grow some backbone**
You are going to be offended or ridiculed from time to time.  Not everyone agrees with everyone.  We do not need special rules for specific groups of people.  We do not need to protect specific groups of people.  Going off of what KirbyKat21 said, _"I don't think having a protected group above general users being outlined in rules like this is smart. It just makes too many lines in the sand and segments the userbase based on their identity."_  That kind of special treatment can also cause separation, segregation, and hatred towards those that have special protection because of who they are, which, if you think about it, is rude and only dehumanizes them further to put them in a special category, wouldn't you think?  There are no groups at risk.  They're only "made at risk" because of people like you trying to shove them into special categories instead of treating them like humans.

**Conclusion**
Grow some backbone and suck it up.  Things happen and it's obvious people very quickly get over a meme or a joke that was made.  The only fights you see are micro-fights that end in mere minutes and are forgotten.  We don't need people pinging moderators and asking them if this is okay.  We don't need tattlers, and we especially don't need to treat other humans better or worse than others.  We're all human, we all have funny things about us that people will joke about, regardless if it's just a stereotype or truth.  And since we're all equally human, I'm positive the majority of people will very well KNOW when something is unacceptable.  And by majority, I mean well over, and read this carefully, _more than two or three people having a 2-3 minute fit over a joke/meme that they move on and forget about by the next day._  We forget things fast, and the only thing that was ruined was that small moment in time.  You have better things to do than to sit around and fume at jokes made by people you don't even know.

That is all.

**Comment by MythicManiac** [comment]
@KomradeSpectre I see a lot of critique coming from your way on this PR without actually proposing alternatives or edits to what should or shouldn't be included. It seems like you and @KomradeSpectre have gotten caught up in what is a small part of the entire draft, rather than viewing it for what it is. While feedback is welcome, I feel like the feedback so far is coming from the wrong place.

The end goal here is that we want to give the community itself more control over the rules by allowing new proposals to be submitted via pull requests and for those proposals to be commented on. I asked @RyanPallesen to produce a draft of what those could be and submit it as a pull request here for review. If something is copypasted directly from the Discord's TOS, that seems like something we don't even really have control over and could be included here for the sake of clarity. It could be mentioned it is directly from the Discord TOS however to avoid this kind of red herring effect.

Also, keep in mind rules don't have to be about just disallowing something, you could propose additions for explicitly allowing certain kinds of discussion or content, like how we now have a rule allowing for NSFW content on the NSFW section.

Ultimately the final say is still going to be in the moderation team's hands, but this way we're able to actually gather input on how does the community itself feel about how moderators should or shouldn't act. While I am the owner of the Discord server, my belief is that it wouldn't be right for me to alone dictate what kinds of content is or isn't allowed. To that end the purpose of this repository and PR is to reduce the responsibility of me and other moderators somewhat in this regard.

**Pull request closed without merging**
